[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dekant_pm = "4GYvtbs7da26tLaZt9PNQWLesq2riwEN6fi9tGF91A5P"

[programs.devnet]
dekant_pm = "4GYvtbs7da26tLaZt9PNQWLesq2riwEN6fi9tGF91A5P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
